# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_model.gru.ipynb (unless otherwise specified).

__all__ = []

# Cell
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)